name: Python QA Control (Pytest + Flake8)

on: push

jobs:
  qualite:
    name: Vérification des tests et style PEP8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Installation des paquets
        run: |
          pip install pytest
          pip install flake8
          
      - name: Lancement des tests
        run: |
          pytest
        run: |
          flake8

      - name: Vérification Flake8
        uses: py-actions/flake8@v2

      # Optionnel - Upload des résultats (version corrigée)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4  # <-- Version mise à jour
        with:
          name: test-results
          path: test-results.xml
